name: flutter_pptx
description: A package for creating pptx files from markdown, widgets or slide templates.
version: 0.1.3
repository: https://github.com/vanphuc06t1/flutter_pptx
homepage: https://github.com/vanphuc06t1/flutter_pptx

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dart_pptx: 
    path: ../dart_pptx/
    version: ^0.1.3
  screenshot: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
