name: dart_pptx
description: A package for creating pptx files from markdown or slide templates.
version: 0.1.3
repository: https://github.com/vanphuc06t1/flutter_pptx
homepage: https://github.com/vanphuc06t1/flutter_pptx

environment:
  sdk: ">=2.17.0 <3.0.0"

executables:
  md2pptx: main

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

dependencies:
  archive: ^3.3.9
  collection: ^1.17.0
  file: ^6.1.4
  http: ^0.13.5
  image_size_getter: ^2.1.2
  json_annotation: ^4.8.0
  mustache_template: ^2.0.0
  path: ^1.8.2
  recase: ^4.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  build_version: ^2.1.1
